steps:
  - id: 'Update version in files'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _NEW_VERSION=${_TOOLBOX_VERSION}
        sed -i "s/_TOOLBOX_VERSION: '.*/_TOOLBOX_VERSION: '$_NEW_VERSION'/" integration.cloudbuild.yaml
        
  - id: 'Create Pull Request'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    env:
      GH_TOKEN: $(gcloud secrets versions access latest --secret=github-pat --project=${_PROJECT_ID})
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y gh
        git config --global user.email "anushkasaxenaa@google.com"
        git config --global user.name "Cloud Build Bot Anushka"
        git config --global url."https://${GH_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        
        BRANCH_NAME="auto-update/toolbox-version-${_TOOLBOX_VERSION}"
        git checkout -b "$BRANCH_NAME"
        # echo "$GH_TOKEN" | gh auth login --with-token
        gh auth status
        git add .
        git commit -m "chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}"
        git push origin "$BRANCH_NAME"
        
        gh pr create --title "chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}" --body "Automated update to version ${_TOOLBOX_VERSION}" --head "$BRANCH_NAME"

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TOOLBOX_VERSION: '0.12.0'
  _PROJECT_ID: anushkasaxenaa-playground
