steps:
  - id: 'Update version in files'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _NEW_VERSION=${_TOOLBOX_VERSION}
        sed -i "s/_TOOLBOX_VERSION: '.*/_TOOLBOX_VERSION: '$_NEW_VERSION'/" integration.cloudbuild.yaml
        
  - id: 'Create Pull Request'
    uses: googleapis/code-suggester@v2
    env:
      # Use the PAT retrieved from Secret Manager to authenticate the action
      ACCESS_TOKEN: $(gcloud secrets versions access latest --secret=github-pat --project=${_PROJECT_ID})
    with:
      command: pr
      branch: 'auto-update/toolbox-version-${_TOOLBOX_VERSION}'
      description: 'Generated in Cloud Build. Automated update to version ${_TOOLBOX_VERSION}.'
      title: 'chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}'
      message: 'chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}'
      force: true
      fork: true
      
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TOOLBOX_VERSION: '0.12.0'
  _PROJECT_ID: anushkasaxenaa-playground
