steps:
  # STEP 0: Get _PAT from Secret Manager
  - id: 'Get _PAT from Secret Manager'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Retrieve the _PAT value and store it as a shell variable.
        _PAT=$(gcloud secrets versions access latest --secret=github-pat --project=${_PROJECT_ID})
        echo "_PAT=$_PAT" >> /workspace/env_vars.txt

  # STEP 1: Update version in files
  - id: 'Update version in files'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env_vars.txt
        NEW_VERSION=${_TOOLBOX_VERSION}
        sed -i "s/_TOOLBOX_VERSION: '.*/_TOOLBOX_VERSION: '$NEW_VERSION'/" integration.cloudbuild.yaml

  # STEP 2: Create Pull Request using Code Suggester
  - id: 'Create Pull Request'
    uses: googleapis/code-suggester@v2
    env:
      ACCESS_TOKEN: $(cat /workspace/env_vars.txt | grep _PAT= | cut -d= -f2)
    with:
      command: pr
      branch: 'auto-update/toolbox-version-${_TOOLBOX_VERSION}'
      description: 'Generated in Cloud Build. Automated update to version ${_TOOLBOX_VERSION}.'
      title: 'chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}'
      message: 'chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}'
      force: true
      fork: true

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TOOLBOX_VERSION: '0.12.0'
  _PROJECT_ID: anushkasaxenaa-playground
  
  
  # steps:
#   - id: 'Update version in files'
#     name: 'ubuntu'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         _NEW_VERSION=${_TOOLBOX_VERSION}
#         sed -i "s/_TOOLBOX_VERSION: '.*/_TOOLBOX_VERSION: '$_NEW_VERSION'/" integration.cloudbuild.yaml
        
#   - id: 'Create Pull Request'
#     name: 'gcr.io/cloud-builders/gcloud'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         # 1. RETRIEVE _PAT & SET ENV VARIABLE
#         # This retrieves the secret value and sets _GH_TOKEN for this shell session.
#         # This must be done inside the step that uses the variable.
#         export _GH_TOKEN=$(gcloud secrets versions access latest --secret=github-pat --project=${_PROJECT_ID})

#         # 2. Configure Git with the _PAT for push authentication
#         git config --global user.email "anushkasaxenaa@google.com"
#         git config --global user.name "Cloud Build Bot Anushka"
#         git config --global url."https://${_GH_TOKEN}@github.com/".insteadOf "https://github.com/"
        
#         # 3. Install the GitHub CLI
#         apt-get update && apt-get install -y gh
        
#         # 4. Create branch and commit changes
#         BRANCH_NAME="auto-update/toolbox-version-${_TOOLBOX_VERSION}"
#         git checkout -b "$BRANCH_NAME"
#         git add .
#         git commit -m "chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}"
#         git push origin "$BRANCH_NAME"
        
#         # 5. Create the PR (Authenticates automatically using _GH_TOKEN env var)
#         gh pr create --title "chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}" --body "Automated update to version ${_TOOLBOX_VERSION}" --head "$BRANCH_NAME"
#         echo "$_GH_TOKEN" | gh auth login --with-token
        
# options:
#   logging: CLOUD_LOGGING_ONLY
# substitutions:
#   _TOOLBOX_VERSION: '0.12.0'
#   _PROJECT_ID: anushkasaxenaa-playground
