steps:
  - id: 'Get PAT from Secret Manager'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _PAT=$(gcloud secrets versions access latest --secret=github-pat --project=${_PROJECT_ID})
        echo "_PAT=$_PAT" >> /workspace/env_vars.txt
        
  - id: 'Update version in files'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env_vars.txt
        NEW_VERSION=${_TOOLBOX_VERSION}
        sed -i "s/_TOOLBOX_VERSION: '.*/_TOOLBOX_VERSION: '$NEW_VERSION'/" integration.cloudbuild.yaml

  - id: 'Create Pull Request'
    uses: googleapis/code-suggester@v2
    env:
      ACCESS_TOKEN: $(cat /workspace/env_vars.txt | grep _PAT= | cut -d= -f2)
    with:
      command: pr
      branch: 'auto-update/toolbox-version-${_TOOLBOX_VERSION}'
      description: 'Generated in Cloud Build. Automated update to version ${_TOOLBOX_VERSION}.'
      title: 'chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}'
      message: 'chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}'
      force: true
      fork: true

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TOOLBOX_VERSION: '0.12.0'
  _PROJECT_ID: anushkasaxenaa-playground
