steps:
  - id: 'Update version in files'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _NEW_VERSION=${_TOOLBOX_VERSION}
        sed -i "s/_TOOLBOX_VERSION: '.*/_TOOLBOX_VERSION: '$_NEW_VERSION'/" integration.cloudbuild.yaml
        
  - id: 'Create Pull Request'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 1. RETRIEVE PAT & SET ENV VARIABLE
        # This retrieves the secret value and sets _GH_TOKEN for this shell session.
        # This must be done inside the step that uses the variable.
        export _GH_TOKEN=$(gcloud secrets versions access latest --secret=pat --project=${_PROJECT_ID})

        # 2. Configure Git with the PAT for push authentication
        git config --global user.email "anushkasaxenaa@google.com"
        git config --global user.name "Cloud Build Bot Anushka"
        git config --global url."https://oauth2:${_GH_TOKEN}@github.com/".insteadOf "https://github.com/"
        
        # 3. Install the GitHub CLI
        apt-get update && apt-get install -y gh
        
        # 4. Create branch and commit changes
        BRANCH_NAME="auto-update/toolbox-version-${_TOOLBOX_VERSION}"
        git checkout -b "$BRANCH_NAME"
        git add .
        git commit -m "chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}"
        git push origin "$BRANCH_NAME"
        
        # 5. Create the PR (Authenticates automatically using _GH_TOKEN env var)
        gh pr create --title "chore(deps): update genai-toolbox version to ${_TOOLBOX_VERSION}" --body "Automated update to version ${_TOOLBOX_VERSION}" --head "$BRANCH_NAME"

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TOOLBOX_VERSION: '0.12.0'
  _PROJECT_ID: anushkasaxenaa-playground
