name: Auto-Update Go Toolbox Version

on:
  repository_dispatch:
    types: [genai-toolbox-update]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version in file
        run: |
          NEW_VERSION=${{ github.event.client_payload.new_version }}
          # Remove the 'v' prefix from the version tag
          NEW_VERSION_CLEAN=$(echo "$NEW_VERSION" | sed 's/^v//')
          
          # Update the single integration.cloudbuild.yaml file at the root
          sed -i "s/_TOOLBOX_VERSION: '.*/_TOOLBOX_VERSION: '$NEW_VERSION_CLEAN'/" integration.cloudbuild.yaml
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
         commit-message: 'chore(deps): update genai-toolbox version to ${{ github.event.client_payload.new_version }}'
         # Corrected title to use the payload directly
         title: 'chore(deps): update genai-toolbox version to ${{ github.event.client_payload.new_version }}'
         body: 'This PR was automatically generated to update the _TOOLBOX_VERSION to ${{ github.event.client_payload.new_version }}.'
         branch: auto-update/go-toolbox-version
